---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: boinc
objects:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: boinc
    labels:
      app: boinc
  spec:
    serviceName: boinc
#    replicas: ${BOINC_CLIENT_NUMBER}
    selector:
      matchLabels:
        app: boinc
    template:
      metadata:
        labels:
          app: boinc
      spec:
        terminationGracePeriodSeconds: 10
        containers:
          - name: boinc
            image: boinc/client
            imagePullPolicy: Always
            env:
            - name: BOINC_CMD_LINE_OPTIONS
              value: "--attach_project ${BOINC_CMD_LINE_OPTIONS_PROJECT} ${BOINC_CMD_LINE_OPTIONS_ACCOUNT_KEY}"
            volumeMounts:
              - mountPath: /var/lib/boinc
                name: boinc
            ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
            - containerPort: 31416
              name: manager
              protocol: TCP
    volumeClaimTemplates:
      - metadata:
          name: boinc
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
parameters:
  - name: BOINC_CLIENT_NUMBER
    displayName: Number of Boinc Clients
    description: Number of Boinc Clients
    required: true
    value: "1"
  - name: BOINC_CMD_LINE_OPTIONS_PROJECT
    displayName: Project
    description: Project
    required: true
    value: "http://boinc.bakerlab.org/rosetta"
  - name: BOINC_CMD_LINE_OPTIONS_ACCOUNT_KEY
    displayName: Account-key
    description: Account-key
    required: true
